#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MemoryTraining.Resource", IsApplication=true)]

namespace MemoryTraining
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int background = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int color_action_bar = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int color_primary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int color_primary_dark = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int color_primary_light = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060003
			public const int big = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int medium = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int small = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int tiny = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int animal_card8 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int card7 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int card8 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cards1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cards112 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cards2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cards3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cards4 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int cards5 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int cards6 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cards7 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cards8 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int game_screen11 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int game_screen9 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_menu_black_24dp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int iconMT = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Logopit1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int testBCardDis1 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int testBCardDis2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int testCard3 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int testCardDis1 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int testCardDis2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int testCardDis3 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int testGame1 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int testGame2 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int testGame3 = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000d
			public const int btn_Continue = 2131296269;
			
			// aapt resource value: 0x7f090001
			public const int btn_easy_difficult = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int btn_exit = 2131296268;
			
			// aapt resource value: 0x7f090004
			public const int btn_find_cards = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int btn_find_words = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int btn_hard_difficult = 2131296259;
			
			// aapt resource value: 0x7f090010
			public const int btn_menu_exit = 2131296272;
			
			// aapt resource value: 0x7f09000a
			public const int btn_new = 2131296266;
			
			// aapt resource value: 0x7f090002
			public const int btn_normal_difficult = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public const int btn_settings = 2131296267;
			
			// aapt resource value: 0x7f09000f
			public const int btn_start_again = 2131296271;
			
			// aapt resource value: 0x7f090009
			public const int button1 = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int gameMenu = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int gridLayout1 = 2131296264;
			
			// aapt resource value: 0x7f090000
			public const int mainContainer = 2131296256;
			
			// aapt resource value: 0x7f09000e
			public const int resultText = 2131296270;
			
			// aapt resource value: 0x7f090006
			public const int text1 = 2131296262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChooseCardDifficult = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChooseTraining = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FindCards = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FindWords = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Menu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ResultMenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int aplodismenty_vne_pomescheniya = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int btn_Continue_text = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int btn_exit_text = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int btn_menu_exit_text = 2131165196;
			
			// aapt resource value: 0x7f070002
			public const int btn_new_text = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int btn_settings_text = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int btn_start_again_text = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int choose_training = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int easy_difficult_text = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int find_cards_label = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int find_words_label = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int hard_hard_text = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int normal_difficult_text = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int result_template = 2131165197;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080003
			public const int ActionBarTheme = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int AppTheme = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int main_background = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int margin_default = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
